
















// RANDOM NAMES

first = [
    "Flex",
    "Plank",
    "Tex",
    "Hunk",
    "Butch",
    "Delt",
    "Bulk",
    "Tank",
    "Wolf",
    "Dunk",
    "Punt",
    "Pinky",
    "Tinkles",
    "Slappy",
    "Girth",
    "Turdsworth",
    "Bold",
    "Chunk",
    "Sleaze",
    "Poop",
    "Splint",
    "Flint",
    "Thick",
    "Blast",
    "Buff",
    "Slam",
    "Fist",
    "Stump",
    "Belch",
    "Clank",
    "Smash",
    "Spooge",
    "Punch",
    "Buck",
    "Dirk",
    "Pork",
    "Rip",
    "Slate",
    "Crud",
    "Gristle",
    "Grunt",
    "Crunch",
    "Slab",
    "Touch",
    "Stank",
    "Nacho",
    "Brock",
    "Ash",
    "Retch",
    "Smoke",
    "Grunt",
    "Ogre",
    "Flap",
    "Deadlift",
    "Beard",
    "Crust",
    "Max",
    "Flank",
    "Buzz",
    "Lump",
    "Lunk",
    "Stump",
    "Mama",
    "Nanna",
    "Daddy",
    "Uncle",
    "Aunt",
    "Auntie",
    "Meadowlark",
    "Leonardo",
    "Michaelangelo",
    "Raphael",
    "Donatello",
    "Shredder",
    "Master",
    "Old Mother",
    "'Tinker' Bill",
    "Ol' Grungy",
    "'Bedsores'",
    "'Gropey'",
    "Happy",
    "Sleepy",
    "Sneezy",
    "Grumpy",
    "Dopey",
    "Doc",
    "Bashful",
    "Old",
    "Ho Chi",
    "Tex",
    "Kansas",
    "Arkansas",
    "'Crusty' Frank",
    "Panthro",
    "Clucklynn",
    "Bredd",
    "Grendel",
    "Bret 'The Hitman'",
    "'Razor'",
    "Canadian Barney",
    "Alabama",
    "Louisiana",
    "Texas",
    "Poppa",
    "Grammy",
    "Granny",
    "Old Man",
    "Grandpa",
    "Grampy",
    "Pepe",
    "Bugsy",
    "Frenchy",
    "Pete",
    "Pepper",
    "Sonny",
    "Smilin' Hank",
    "'Macho Man' Randy",
    "Crunch",
    "Hoss",
    "Heck",
    "Diablo",
    "Tequila",
    "Sally",
    "Pinky",
    "Tinkles",
    "Rainbow",
    "Shorty",
    "Yokozuna",
    "'Nature Boy' Ric",
    "Leatherface",
    "One-Eyed Jim",
    "Skinny",
    "Lysergia",
    "Stinky",
    "Smelly",
    "Slappy",
    "Trollo",
    "Frodo",
    "Legolas",
    "Pippin",
    "Baphomet",
    "Tiamat",
    "Baldy",
    "Emeril",
    "Fat Rocco",
    "Deadeye",
    "Aragorn",
    "Sauron",
    "Hork",
    "Hunk",
    "Hulk",
    "Hurk",
    "Salty",
    "'Flatulent' Mike",
    "Dirty Doug",
    "Hacksaw Jim",
    "Ted 'The Million Dollar Man'",
    "'Junkyard'",
    "Whiskey Pete",
    "Vodka Sam",
    "Homeless Dan",
    "Arkansas Dave",
    "Magic",
    "Artie",
    "Prison Bob",
    "Hulk",
    "'Handsome' Harry",
    "'Sloppy' Charlie",
    "Drunken Bill",
    "Jose",
    "Grizzly",
    "Hannibal",
    "Tequila Slim",
    "Slim",
    "Skinny Nate",
    "Lo Pan",
    "'Nasty' Dan",
    "'Honest' Irving",
    "'Ragged' Dick",
    "Professor",
    "Father",
    "Bishop",
    "King",
    "Sir Elton",
    "Yolo",
    "Freckles",
    "Taint",
    "Mama",
    "Nanna",
    "Daddy",
    "Uncle",
    "Aunt",
    "Auntie",
    "Meadowlark",
    "Leonardo",
    "Michaelangelo",
    "Raphael",
    "Donatello",
    "Shredder",
    "Master",
    "Old Mother",
    "'Tinker' Bill",
    "Ol' Grungy",
    "'Bedsores'",
    "'Gropey'",
    "Happy",
    "Sleepy",
    "Sneezy",
    "Grumpy",
    "Dopey",
    "Doc",
    "Bashful",
    "Old",
    "Ho Chi",
    "Tex",
    "Kansas",
    "Arkansas",
    "'Crusty' Frank",
    "Panthro",
    "Clucklynn",
    "Bredd",
    "Grendel",
    "Bret 'The Hitman'",
    "'Razor'",
    "Canadian Barney",
    "Alabama",
    "Louisiana",
    "Texas",
    "Poppa",
    "Grammy",
    "Granny",
    "Old Man",
    "Grandpa",
    "Grampy",
    "Pepe",
    "Bugsy",
    "Frenchy",
    "Pete",
    "Pepper",
    "Sonny",
    "Smilin' Hank",
    "'Macho Man' Randy",
    "Crunch",
    "Hoss",
    "Heck",
    "Diablo",
    "Tequila",
    "Sally",
    "Pinky",
    "Tinkles",
    "Rainbow",
    "Shorty",
    "Yokozuna",
    "'Nature Boy' Ric",
    "Leatherface",
    "One-Eyed Jim",
    "Skinny",
    "Lysergia",
    "Stinky",
    "Smelly",
    "Slappy",
    "Trollo",
    "Frodo",
    "Legolas",
    "Pippin",
    "Baphomet",
    "Tiamat",
    "Baldy",
    "Emeril",
    "Fat Rocco",
    "Deadeye",
    "Aragorn",
    "Sauron",
    "Hork",
    "Hunk",
    "Hulk",
    "Hurk",
    "Salty",
    "'Flatulent' Mike",
    "Dirty Doug",
    "Hacksaw Jim",
    "Ted 'The Million Dollar Man'",
    "'Junkyard'",
    "Whiskey Pete",
    "Vodka Sam",
    "Homeless Dan",
    "Arkansas Dave",
    "Magic",
    "Artie",
    "Prison Bob",
    "Hulk",
    "'Handsome' Harry",
    "'Sloppy' Charlie",
    "Drunken Bill",
    "Jose",
    "Grizzly",
    "Hannibal",
    "Tequila Slim",
    "Slim",
    "Skinny Nate",
    "Lo Pan",
    "'Nasty' Dan",
    "'Honest' Irving",
    "'Ragged' Dick",
    "Professor",
    "Father",
    "Bishop",
    "King",
    "Sir Elton",
    "Yolo",
    "Barack",
    "George W.",
    "William Jefferson",
    "George H.W.",
    "Ronald",
    "Jimmy",
    "Gerald R.",
    "Richard Milhouse",
    "Lyndon B.",
    "John Fitzgerald",
    "Dwight David",
    "Harry S",
    "Franklin Delano",
    "Herbert",
    "Calvin",
    "Woodrow",
    "Howard",
    "Theodore",
    "William",
    "Grover",
    "Benjamin",
    "Chester A.",
    "James",
    "Rutherford B.",
    "Ulysses S.",
    "Andrew",
    "Abraham",
    "Jimbo",
    "Franklin",
    "Millard",
    "James K.",
    "Zachary",
    "William Henry",
    "Martin Van",
    "Thomas J.",
    ]
    
    
    last_a = [
    "Mc",
    "O'",
    "Vander",
    "Von ",
    "Stoop",
    "Flip",
    "Flap",
    "Flop",
    "Whack",
    "Horn",
    "Swag",
    "Swack",
    "Dumble",
    "Flax",
    "Plank",
    "Thrust",
    "Cheese",
    "Butt",
    "Fish",
    "Fist",
    "Slap",
    "Crust",
    "Waggle",
    "Shit",
    "Crap",
    "Dank",
    "Smoke",
    "Thrust",
    "Horn",
    "Shart",
    "Grunt",
    "Crank",
    "Crack",
    "Dill",
    "Dick",
    "Rocket",
    "Thwack",
    "Thunder",
    "Cradle",
    "Peck",
    "Flock",
    "Heisen",
    "Curdle",
    "Big",
    "Hender",
    "Funk",
    "Bork",
    "Babble",
    "Mc",
    "O'",
    "Vander",
    "Von ",
    "Ham",
    "Bulge",
    "Turd",
    "Grunge",
    "Hard",
    "Rock",
    "Thunder",
    "Goat",
    "Corpse",
    "Squat",
    "Dead",
    "Flap",
    "Dope",
    "Man",
    "Weed",
    "Stab",
    "Smash",
    "Frog",
    "Thorn",
    "Junk",
    "Speed",
    "Iron",
    "Crap",
    "Shit",
    "Full",
    "Doom",
    "Cock",
    "Fridge",
    "Beard",
    "Sheep",
    "Lamb",
    "Muffin",
    "Stank",
    "Cream",
    "Piss",
    "Butter",
    "Hunch",
    "Blood",
    "Huge",
    "Pain",
    "Chunky",
    "Ball",
    "Straw",
    "Fart",
    "Drunk",
    "Death",
    "Filth",
    "Rage",
    "Back",
    "Jizz",
    "Nasty",
    "Bullet",
    "Sour",
    "Filth",
    "Whore",
    "War",
    "St. ",
    "Ass",
    "Thick"
    ]
    last_b = [
    "stump",
    "nagle",
    "hump",
    "fish",
    "swag",
    "son",
    "blast",
    "scrote",
    "man",
    "pickle",
    "trickle",
    "tickle",
    "wangle",
    "dingle",
    "dangle",
    "dongle",
    "cringle",
    "splurge",
    "gurgle",
    "frapp",
    "slort",
    "slank",
    "slonk",
    "bonk",
    "rabble",
    "scrabble",
    "babble",
    "dabble",
    "flabble",
    "slice",
    "bloop",
    "slurp",
    "hammer",
    "scoop",
    "flex",
    "splurge",
    "splat",
    "whopple",
    "whopper",
    "ington",
    "meister",
    "puncher",
    "bust",
    "brother",
    "baum",
    "berg",
    "pan",
    "grizzle",
    "fuzz",
    "berger",
    "slap",
    "fist",
    "master",
    "swaddle",
    "crank",
    "whizzle",
    "dizzle",
    "doodle",
    "dang",
    "shart",
    "wang",
    "diddle",
    "fizzle",
    "puzzle",
    "chunder",
    "squiggle",
    "lord",
    "cram",
    "bang",
    "stank",
    "shove",
    "shizzle",
    "dizzle",
    "drizzle",
    "faddle",
    "fiddle",
    "paddle",
    "piddle",
    "wiggle",
    "noob",
    "can",
    "bottle",
    "thick",
    "slop",
    "whiz",
    "whizzle",
    "blart",
    "long",
    "slurp",
    "flarp",
    "scrizzle",
    "scrunch",
    "blorp",
    "blerp",
    "blob",
    "bland",
    "land",
    "snort",
    "Slab",
    "Meal",
    "Body",
    "Punch",
    "Puke",
    "Child",
    "Stank",
    "Shriek",
    "Chunks",
    "Grease",
    "Priest",
    "Muffin",
    "Cock",
    "Butcher",
    "Flex",
    "chortle",
    "whiz",
    "peeps",
    "beef",
    "hole",
    "dragon",
    "nards",
    "Stump",
    "Fizzle",
    "Shaver",
    "Slave",
    "Mustard",
    "Farts",
    "Fart",
    "Anus",
    "Slice",
    "Nasty",
    "Filth",
    "Curl",
    "Rod",
    "Breath",
    "Crotch",
    "Slayer",
    "Saint",
    "Quad",
    "Lift",
    "Goblin",
    "Smack",
    "Weed",
    "Puncher",
    "Balls",
    "Nose",
    "Chunk",
    "Thrust",
    "Soup",
    "Pork",
    "Fucker",
    "Slap",
    "Pig",
    "Horse",
    "Dog",
    "Wolf",
    "Lion",
    "Corpse",
    "Lust",
    "Sauce",
    "Butt",
    "Baby",
    "Whore",
    "Delt",
    "Hump",
    "Flap",
    "Muscle",
    "Weiner",
    "Burger",
    "Sack",
    "Scrote",
    "Beard",
    "Shot",
    "Loin",
    "Large",
    "Chest",
    "Snack",
    "Snatch",
    "Cheese",
    "Break",
    "Jaw",
    "Dragon",
    "Master",
    "Bone",
    "Purge",
    "Fart",
    "Brain",
    "Midget",
    "Slaughter",
    "Turd",
    "Nipples",
    "Pec",
    "Wang",
    "Face",
    "Boner",
    "Cheek",
    "Iron",
    "Broth",
    "Fist",
    "Vomit",
    "Beef",
    "Back",
    "Penis",
    "Stab",
    "Lips",
    "Lord",
    "Waffle",
    "Monger",
    "Demon",
    "Gremlin",
    "Dope",
    "Guns",
    "Buns",
    "Shart",
    "Stag",
    "stump",
    "nagle",
    "hump",
    "swag",
    "son",
    "blast",
    "scrote",
    "man",
    "pickle",
    "trickle",
    "tickle",
    "wangle",
    "dingle",
    "dangle",
    "dongle",
    "cringle",
    "splurge",
    "gurgle",
    "frapp",
    "slort",
    "slank",
    "slonk",
    "bonk",
    "rabble",
    "scrabble",
    "babble",
    "dabble",
    "flabble",
    "slice",
    "bloop",
    "slurp",
    "hammer",
    "scoop",
    "flex",
    "splurge",
    "splat",
    "whopple",
    "whopper",
    "ington",
    "meister",
    "puncher",
    "bust",
    "brother",
    "baum",
    "berg",
    "pan",
    "grizzle",
    "fuzz",
    "berger",
    "slap",
    "fist",
    "master",
    "swaddle",
    "crank",
    "whizzle",
    "dizzle",
    "doodle",
    "dang",
    "shart",
    "wang",
    "diddle",
    "fizzle",
    "puzzle",
    "chunder",
    "squiggle",
    "lord",
    "cram",
    "bang",
    "stank",
    "shove",
    "shizzle",
    "dizzle",
    "drizzle",
    "faddle",
    "fiddle",
    "paddle",
    "piddle",
    "wiggle",
    "noob",
    "can",
    "bottle",
    "thick",
    "slop",
    "whiz",
    "whizzle",
    "blart",
    "long",
    "slurp",
    "flarp",
    "scrizzle",
    "scrunch",
    "blorp",
    "blerp",
    "blob",
    "bland",
    "land",
    "snort",
    
    ]

    function rando(wordList) {
        const randomChoice = wordList[Math.floor(Math.random()*wordList.length)];
        return randomChoice;
        }
    

    function randomName() {
        const randFirst = rando(first);
        const randLastA = rando(last_a);
        const randLastB = rando(last_b).toLowerCase();
        return(`${randFirst} ${randLastA}${randLastB}`);
    }


    const testimonialsContainer = document.querySelector('.testimonials-container');
    const testimonial = document.querySelector('.testimonial');
    const userImage = document.querySelector('.user-image');
    const username = document.querySelector('.username');
    const role = document.querySelector('.role');

    function randomPhoto() {
        const randNum = Math.floor(Math.random() * 70);
        return randNum;
    }
    
    function randomPerson() {
        const randPerson = Math.floor(Math.random() * 10 + 1)
        if(randPerson <= 5) {
            return "men"
        } else {
            return "women"
        };
    };
    
    const testimonials = [
        {
            name: `${randomName()}`,
            position: 'Porkshire',
            photo: `https://randomuser.me/api/portraits/${randomPerson()}/${randomPhoto()}.jpg`,
            text: "Friendly staff, great prices, and a cozy atmosphere.  I have to say nothing feels better than popping down to the pub and getting a Dickens Cider",
        },
        {
            name: `${randomName()}`,
            position: 'West Swineham',
            photo: `https://randomuser.me/api/portraits/${randomPerson()}/${randomPhoto()}.jpg`,
            text: "Oi bruv.  I like getting my Dickens Cider on the reg.  Cheerio!",
        },
        {
            name: `${randomName()}`,
            position: 'Dingleshire',
            photo: `https://randomuser.me/api/portraits/${randomPerson()}/${randomPhoto()}.jpg`,
            text: "crinkle crango assume flarble wadstasher. fuckreddener bribble blowtester assmunchpolisher? falgo presume tickle slarpo marpo durble vomitsplitter areoleparasailor! extension nip dongsplitter weeddirector barf nooplop equip? EFFICIENT walgo reichhanger screep winkle overview dimwitreinforcer. screedle furtive. florks coitalsurfeiter pubepeddler release walgo JUST GIVE A SQUIRT hurble flapple climaxfisherman timely blang prudewhore! 60 DOLLAR UNPROVEN DVD plerp floom sleazeshielder roopdie proliferation. nadobstructer EFFICIENT",
        },
        {
            name: `${randomName()}`,
            position: 'Southnorth Halfwest Kingsballs',
            photo: `https://randomuser.me/api/portraits/${randomPerson()}/${randomPhoto()}.jpg`,
            text: "Penis joke.",
        },
    ]

    let idx = 1;
    
    function updateTestimonial() {
        const { name, position, photo, text} = testimonials[idx];

        testimonial.innerHTML = text;
        userImage.src = photo;
        username.innerHTML = name;
        role.innerHTML = position;

        idx++

        if(idx > testimonials.length - 1) {
            idx = 0
        }
        
    }

    setInterval(updateTestimonial, 10000);
    
    